---
- name: Install Wireguard repo (Debian)
  apt_repository:
    repo: 'deb http://deb.debian.org/debian buster-backports main'
    state: present
    update_cache: yes
  when: ansible_distribution == 'Debian'

- name: WireGuard installed
  apt:
    name: wireguard
    state: present
    default_release: buster-backports
    update_cache: true

- name: WireGuard reload-module-on-update
  file:
    dest: /etc/wireguard/.reload-module-on-update
    state: touch

- name: Configure unattended-upgrades
  copy:
    src: 50-wireguard-unattended-upgrades
    dest: /etc/apt/apt.conf.d/50-wireguard-unattended-upgrades
    owner: root
    group: root
    mode: 0644

- name: Set OS specific facts
  set_fact:
    service_name: "wg-quick@{{ wireguard_interface }}"
  tags: always
