---
# Built from @dan-v's algo pihole fork

- block:
    - name: Create pihole group
      become: True
      group:
        name="{{ group_pihole }}"
        state=present

    - name: Create pihole user
      become: True
      user:
        name="{{ user_pihole }}"
        group="{{ group_pihole }}"
        groups="{{ group_pihole }}"
        comment="ad filtering DNS proxy"
        system=True
        shell="/usr/sbin/nologin"

    - name: Download pihole installer
      get_url:
          url: https://raw.githubusercontent.com/pi-hole/pi-hole/master/automated%20install/basic-install.sh
          dest: ~/install-pihole.sh
          mode: 0740

    - name: Create pihole config directory
      become: True
      file:
        name="/etc/pihole"
        state=directory
        owner="{{ user_pihole }}"
        group="{{ group_pihole }}"
        mode=0755

    - name: Create pihole configuration
      become: True
      template:
        src="setupVars.conf.j2"
        dest="/etc/pihole/setupVars.conf"
        owner=root
        group=root
        mode=0644

    - name: Create adlist restore
      include_tasks: listrestore.yml

    - name: Install pihole
      command: "~/install-pihole.sh --unattended"
      register: dbg_install_pihole

    - name: Create wildcard scripts
      include_tasks: wildcards.yml

    - name: Create pihole updater
      cron:
        name: "Update pihole"
        special_time: daily
        job: "pihole -up"

    - name: Restart pihole-FTL on reboot
      cron:
        name: "Restart pihole-FTL"
        special_time: reboot
        job: "sleep 5 && /usr/sbin/service pihole-FTL restart"
  rescue:
    - include_tasks: playbooks/rescue.yml

- name: Add LAN DNS hosts dnsmasq file
  copy:
    dest: /etc/dnsmasq.d/02-lan.conf
    content: "addn-hosts=/etc/pihole/lan.list"

- name: Add Pi-hole hosts
  template:
    src: lan.list.j2
    dest: /etc/pihole/lan.list
    owner: root
    group: root
    mode: 0644
    force: yes
  notify:
   - restart pihole-FTL
  tags: update-users

- name: Pause to account for CPU bursting
  pause:
    prompt: "Pause to bring down CPU bursting"
    seconds: 30

- meta: flush_handlers
